// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC89kr71q-bjnMPAA2Wtq6lZs5KqAjqjI',
    appId: '1:594133998274:web:30bf413f39df305880795b',
    messagingSenderId: '594133998274',
    projectId: 'ecolink-app-198ed',
    authDomain: 'ecolink-app-198ed.firebaseapp.com',
    storageBucket: 'ecolink-app-198ed.firebasestorage.app',
    measurementId: 'G-FJM64JXSWT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfeIG2XwdBoFYry5RNMMMm4K9jIP-hrZk',
    appId: '1:594133998274:android:f85613d077c3678280795b',
    messagingSenderId: '594133998274',
    projectId: 'ecolink-app-198ed',
    storageBucket: 'ecolink-app-198ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0WvPANkFBspHis2d9oXJuGHH6NXnttO0',
    appId: '1:594133998274:ios:436c6545307d259d80795b',
    messagingSenderId: '594133998274',
    projectId: 'ecolink-app-198ed',
    storageBucket: 'ecolink-app-198ed.firebasestorage.app',
    iosBundleId: 'com.example.ecolink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0WvPANkFBspHis2d9oXJuGHH6NXnttO0',
    appId: '1:594133998274:ios:436c6545307d259d80795b',
    messagingSenderId: '594133998274',
    projectId: 'ecolink-app-198ed',
    storageBucket: 'ecolink-app-198ed.firebasestorage.app',
    iosBundleId: 'com.example.ecolink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAC89kr71q-bjnMPAA2Wtq6lZs5KqAjqjI',
    appId: '1:594133998274:web:30bf413f39df305880795b',
    messagingSenderId: '594133998274',
    projectId: 'ecolink-app-198ed',
    authDomain: 'ecolink-app-198ed.firebaseapp.com',
    storageBucket: 'ecolink-app-198ed.firebasestorage.app',
    measurementId: 'G-FJM64JXSWT',
  );

  static const String googlePlacesApiKey = 'AIzaSyDfeIG2XwdBoFYry5RNMMMm4K9jIP-hrZk';
}
